// -*- C++ -*-
// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================
#ifndef EVENT_LCINTVEC_H
#define EVENT_LCINTVEC_H 1

#include "EVENT/LCObject.h"
#include "LCIOSTLTypes.h"

 #include "IMPL/AccessChecked.h" // FIXME: EVENT shouldn't  depend on IMPL ...

namespace EVENT {

/** Int vector used for user extensions.
 * The cpp implementation is a std::vector<int>
 * 
 * @author gaede 
 * @version Aug 8, 2003
 * @see LCObject
 */
class LCIntVec : public LCObject, public IntVec {

public: 
    /// Destructor.
    ~LCIntVec() override { /* nop */; }


    using lcobject_type = EVENT::LCIntVec ;

    public:
      int id() const override { return _acc.simpleUID() ; } 
    protected:
      IMPL::AccessChecked _acc{} ;
}; // class
} // namespace EVENT
#endif /* ifndef EVENT_LCINTVEC_H */
